server:
  port: 8080

spring:
  application:
    name: websecurity-lab

  datasource:
    url: jdbc:h2:mem:securitylab;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      platform: h2
      data-locations: ["classpath:data.sql"]

  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.lab.security: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG


app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200

---
spring:
  config:
    activate:
      on-profile: vulnerable

  datasource:
    url: jdbc:h2:mem:securitylab;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always
      platform: h2
      data-locations: ["classpath:data.sql"]

logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.security: WARN

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
